name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and build
        working-directory: ./word-combo-angular
        run: npm install && npm run gh-build && cp dist/word-combo-angular/index.html dist/word-combo-angular/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: word-combo-angular/dist/word-combo-angular # The folder the action should deploy.

